name: store_gui_app
description: "WhatsApp Status Downloader with AdMob"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

  # Monetization
  google_mobile_ads: ^5.3.1

  # File Picker for SAF Storage Selection
  file_picker: ^8.3.7
  saf: ^1.0.4

  # Real-time Video Thumbnail Renderer (Corrected Version)
  video_thumbnail_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icon/app_logo.png

flutter:
  uses-material-design: true
